# Generated by Django 4.0.2 on 2022-03-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='todoList',
            new_name='requestList',
        ),
    ]
