# Generated by Django 4.0.2 on 2022-03-07 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0002_rename_todolist_request_requestlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='request',
            name='requestList',
        ),
        migrations.RemoveField(
            model_name='request',
            name='text',
        ),
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RequestList',
        ),
    ]
