# Generated by Django 4.0.2 on 2022-03-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_remove_request_name_remove_request_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlist',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='eventDescription',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='eventEndDate',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='eventLocation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='eventStartDate',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='eventStatus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='eventType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='port',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='reportingCycle',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='requestlist',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requestlist',
            name='classification',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
