# Generated by Django 4.0.2 on 2022-04-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_alter_requestlist_options_delete_request'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requestlist',
            table='requestlist',
        ),
    ]
