# Generated by Django 4.0.2 on 2022-03-09 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_alter_request_options_alter_requestlist_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='request',
            table='request',
        ),
        migrations.AlterModelTable(
            name='requestlist',
            table='requestlist',
        ),
    ]
